---

- name: Setting up DNS
  tags:
    - dnssetup
  block:
    - name: Copy DNS python server
      ansible.posix.synchronize:
        src: dns/
        dest: /data/happy-eyeballs-test/dns/
        owner: false
        group: false

    - name: Copy DNS server service file
      ansible.builtin.template:
        src: he-dns-server.service.j2
        dest: /etc/systemd/system/he-dns-server.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd and start DNS server
      ansible.builtin.systemd_service:
        name: he-dns-server.service
        daemon_reload: true
        state: restarted
